### PR TITLE
Windows deep links

### PR DESCRIPTION
**Pull request by SimonSimCity**
Tested on MacOS (Intel) and Windows

### CODE REVIEW

**Comment by SimonSimCity** [comment]
It seems the protocol is not registered during installation of the app (https://stackoverflow.com/questions/45809064/registering-custom-protocol-at-installation-process-in-electron-app) - which opens another question for me:

Is the protocol only registered while running the app, or is it registered on first start and also usable when the app is not running?

To answer this question, I need an installable build.

**Comment by SimonSimCity** [comment]
On MacOS and Windows the protocol is registered after opening it for the first time.

With the latest changes the app doesn't crash anymore on MacOS if the last window is closed; opening deep-links without having the app running works also as expected, so MacOS is working 😎🎉

Windows now also works mostly. The only downside is that the app starts with the main page when opened by a deep-link. It opens the correct page when opening a deep-link while the app is running though... Still needs some fine-tuning here...

**Review by kkuepper — COMMENTED** [review]
Now everything is in main.ts. It would be nice to extract the part with deeplinking into it's own file.

**Comment by SimonSimCity** [comment]
> Now everything is in `main.ts`. It would be nice to extract the part with deep-linking into it's own file.

Well ... that's almost be the whole file ... Feel free to split it up as you see it fit though 🤗

**Review by kkuepper — APPROVED** [review]

**Pull request merged**
