### PR TITLE
Use current-color in svgs

### PR DESCRIPTION
**Pull request by SimonSimCity**
Avoid the usage of css to define a color on an svg image, but rather in SVG use `currentColor`.

### CODE REVIEW

**Comment by SimonSimCity** [comment]
In the preview I could see that the following images have a change:

Fill:
* assets/icons/download.svg
* assets/icons/icon.loading (animation).svg
* assets/icons/queue.svg

Color:
* assets/icons/nav.browse.svg
* assets/icons/nav.favorites.svg
* assets/icons/nav.home.svg
* assets/icons/nav.ios.browse.svg
* assets/icons/nav.ios.favorites.svg
* assets/icons/nav.ios.home.svg
* assets/icons/nav.ios.library.svg
* assets/icons/nav.ios.profile.svg
* assets/icons/nav.ios.search.fill.svg
* assets/icons/nav.library.svg
* assets/icons/nav.profile.svg
* assets/icons/nav.search.svg

I was also surprised how many duplicates we actually have among those images... @sclausen is there a common procedure of extracting those images from Figma, or is there a reason why so many images are duplicated?

**Review by sifferhans — CHANGES_REQUESTED** [review]
Looks good! There are a couple of icons with unnecessary fills though:
- download.svg
- icon.loading (animation).svg

Other than that, looks good!

**Review by sifferhans — CHANGES_REQUESTED** [review]
These still don't look right to me

CleanShot 2023-12-13 at 15 55 59

CleanShot 2023-12-13 at 15 56 18

**Comment by sclausen** [comment]
@SimonSimCity are you really referring to me? I have to admit that I have absolutely no memory participating in this project at all.

**Comment by SimonSimCity** [comment]
@sclausen sorry for pulling you in here, I had a typo in the username 🙈

**Comment by SimonSimCity** [comment]
@sifferhans the two files you're referring to are not part of the changed files anymore - they're just part of individual commits 🤗

**Comment by sifferhans** [comment]
@SimonSimCity Ah, right! Then everything looks good to me 😁

**Review by sifferhans — APPROVED** [review]

**Pull request merged**
