### PR TITLE
Add tailwind tokens

### PR DESCRIPTION
**Pull request by steffanhalv**
Feel free to implement this tokens provided by Søren, I did not get much time for it 😅 @sifferhans 

Ref. #24

### CODE REVIEW

**Comment by sifferhans** [comment]
Nice! I'll look at it 😁

**Review by sifferhans — CHANGES_REQUESTED** [review]
Can you place the files in the /asssets directory instead of /resources? 😊

**Comment by steffanhalv** [comment]
> Can you place the files in the /asssets directory instead of /resources? 😊

Done 👍😊

**Comment by sifferhans** [comment]
This will be closed by #94

**Comment by kkuepper** [comment]
I'm closing this since it's replaced by #94

**Pull request closed without merging**
