### PR TITLE
Search composable file created

### PR DESCRIPTION
**Pull request by belljohan3**

### CODE REVIEW

**Comment by SimonSimCity** [comment]
Would be nice if you could add this to the place where this function is used. I'd wait for this PR before merging this.

**Comment by belljohan3** [comment]
@SimonSimCity what do you mean when you say the place ?

**Comment by SimonSimCity** [comment]
@belljohan3 currently this PR would add some code which is not used. The changes look good, but they do not add a value yet, because the code you added is not used. I'd merge this PR when you add this function and call it somewhere where the user can use it 😊

**Comment by SimonSimCity** [comment]
Am merging this now. It's already adding some value which we haven't had yet. Additional improvements on this can be provided in other PRs and you're very welcome and encouraged to provide additional value.

**Comment by belljohan3** [comment]
Ok @SimonSimCity. Thanks a lot.

**Pull request merged**
