### PR TITLE
Initialize base for a good start of the project

### PR DESCRIPTION
**Pull request by SimonSimCity**
- [x] Initialize the project using vite
- [ ] Update TypeScript config to use tight typing
- [ ] Write first blackbox-tests for components
- [ ] Init Pinia
- [ ] Streamline configs with the repo [brunstadtv](https://github.com/bcc-code/brunstadtv/tree/develop/web)
- [ ] Set up groundwork for continuous integration

### CODE REVIEW

**Comment by kkuepper** [comment]
@SimonSimCity looks good so far. Do you want me to merge that or do you first want to address the other tasks?

**Comment by kkuepper** [comment]
What do you mean by "Set up groundwork for continuous integration"?
I would expect a yaml file like https://github.com/bcc-code/BMM-Website/blob/develop/.github/workflows/pipeline.yml .

**Comment by SimonSimCity** [comment]
> What do you mean by "Set up groundwork for continuous integration"? I would expect a yaml file like https://github.com/bcc-code/BMM-Website/blob/develop/.github/workflows/pipeline.yml .

To me this goes further than just GitHub pipelines (those could also be for CD) - but rather to decide what should be included for continuous integration and implement it. This gets to having commands which allow for automated code-quality-checks, maybe vulnerability scanning, running tests, etc, before it gets to how to execute them automatically.

**Comment by SimonSimCity** [comment]
> @SimonSimCity looks good so far. Do you want me to merge that or do you first want to address the other tasks?

I'd like to address all the tasks in this PR, but thought of rather waiting on a conclusion on the discussion we're having on discord about the technology to use.

**Comment by sifferhans** [comment]
Cool to see this project is getting started!
What's the reason you'll use Vite directly instead of a full-stack alternative like [Nuxt](https://nuxt.com)? Customizability?

**Comment by SimonSimCity** [comment]
@sifferhans What would be a reason for going for a full-stack if we have a backend already in place? I'm open to discuss it, but I'd move to another channel than here on this PR :)

**Review by steffanhalv — APPROVED** [review]

**Review by kkuepper — APPROVED** [review]

**Pull request merged**
