### PR TITLE
65 design for player

### PR DESCRIPTION
**Pull request by BeastiW**
#65  fixes all remaining checkmarks except of the last bullet point.

### CODE REVIEW

**Review by SimonSimCity — APPROVED** [review]

**Comment by SimonSimCity** [comment]
The marquee of the text is quite good, but there are still cases where it could do the wrong thing, e.g. when resizing the page (maybe also when changing orientation on a tablet). As of now, I'd say that's rather over-engineering - but if anyone has a better approach, I'd be happy to take it.

Does this PR also solve the marquee of meta-data in the queue and in the mini-player?

**Comment by kkuepper** [comment]
if the text doesn't need scrolling, it's now left aligned. Is there a way to make it centered?

**Review by kkuepper — CHANGES_REQUESTED** [review]
looks quite distracting if it's not centered

**Review by kkuepper — APPROVED** [review]
looks awesome! Well done!

**Pull request merged**
