### PR TITLE
Feat/electron

### PR DESCRIPTION
**Pull request by steffanhalv**
This "works" except that authentication is blocked for some reason after build.
I will investigate the build further, but I think it is ready to be merged as a starting point.

### CODE REVIEW

**Comment by kkuepper** [comment]
@steffanhalv can you merge main into your branch?

**Comment by steffanhalv** [comment]
> @steffanhalv can you merge main into your branch?

Done

**Comment by kkuepper** [comment]
The linter is complaining. You can check it locally with `pnpm lint`. Shall I fix the issues?

**Comment by steffanhalv** [comment]
> The linter is complaining. You can check it locally with `pnpm lint`. Shall I fix the issues?

Fixed now

**Review by kkuepper — APPROVED** [review]

**Pull request merged**
