### PR TITLE
Fix electron login on built version and other small adjustments...

### LINKED ISSUE #71: setup electron

### PR DESCRIPTION
**Pull request by SimonSimCity**
* Use electrons error-message if there's an error
* Fix login redirection
* Add app-icon

Fixes #71

### CODE REVIEW

**Comment by SimonSimCity** [comment]
Maybe a good option to include the build also in the checks ... it shouldn't fail, but it might 😅 It would also always give us an artifact to work with 😏

**Comment by SimonSimCity** [comment]
After merging all these changes, everyone having write-access should be able to manually run the workflow `Build/release app` from within the `Actions` panel.

**Review by kkuepper — APPROVED** [review]

**Comment by kkuepper** [comment]
@steffanhalv Do you by chance know how to force a new login? Reinstalling didn't ask me to login again making it annoying to work with the login.

**Comment by steffanhalv** [comment]
I think we probably should add a logout button

**Comment by SimonSimCity** [comment]
@kkuepper We could just implement the `logout` function of the auth0 plugin 😏

**Pull request merged**
